version: "3.8"
services:
  #proxy:
  #  image: traefik:2.4
  #  command: --providers.docker.swarmMode --api.insecure
  #  ports:
  #   - 80:80
  #   - 443:443
  #   - 8080:8080
  #  volumes:
  #   - /var/run/docker.sock:/var/run/docker.sock
  cache:
    image: redis
  db:
    image: postgres:13
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsco
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
networks:
  default:
    name: proxy
