version: "3.8"
services:
  proxy:
    image: traefik:2.4
    command: --providers.docker.swarmMode --api.insecure
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    image: rahilshah/bsco:latest
    networks:
      - proxy
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsco
    deploy:
      labels:
        traefik.http.routers.app.rule: Host(`app.localhost`)
        traefik.http.services.app.loadbalancer.server.port: 5000
  cache:
    image: redis
    networks:
      - proxy
  db:
    image: postgres
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - proxy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsco
networks:
  default:
    name: proxy
