version: "3.8"
services:
  app:
    image: rahilshah/bsco:latest
    ports:
      - 5000:5000
    networks:
      - proxy
    environment:
      DB_HOST: db
      REDIS_HOST: cache
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsco
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../bsco/build:/var/www
      - ./data/nginx/:/etc/nginx/conf.d/
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - proxy
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
networks:
  proxy:
    external: true
