version: "3.8"
services:
  app:
    image: rahilshah/bsco:latest
    ports:
      - 5000:5000
    networks:
      - proxy
    environment:
      DB_HOST: db
      REDIS_HOST: cache
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsco
    deploy:
      labels:
        traefik.http.routers.app.rule: Host(`localhost`)
        traefik.http.services.app.loadbalancer.server.port: 5000
  cache:
    image: redis
    ports:
      - 6379:6379
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=false"
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=false"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bsco
networks:
  proxy:
    external: true
